# Generated by Django 2.2.5 on 2019-10-10 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='img_path',
            field=models.ImageField(default='project-default.png', upload_to='images/'),
        ),
    ]
