# Generated by Django 2.2.5 on 2019-10-02 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(default=''),
        ),
    ]
